---
  dependencies:
    - role: ANXS.postgresql
      become: true
      postgresql_version: 9.5
      postgresql_encoding: 'UTF-8'
      postgresql_locale: 'en_US.UTF-8'
      postgresql_admin_user: "postgres"
      postgresql_default_auth_method: "trust"
      postgresql_listen_addresses: '*'
      postgresql_pg_hba_trust_hosts: "{{database_trusted_hosts}}"
      postgresql_users:
      - name: "{{database_username}}"
        pass: "{{database_password}}"
        encrypted: no

      postgresql_databases:
      - name: "{{database_name}}_{{rails_env}}"
        owner: "{{database_username}}"

      postgresql_user_privileges:
      - name: "{{database_username}}"
        db: "{{database_name}}_{{rails_env}}"
        priv: "ALL"
        role_attr_flags: "CREATEDB"
