---
  dependencies:
    - role: rvm_io.rvm1-ruby
      tags: ruby
      become: yes
      rvm1_rubies:
        - 'ruby-2.3.1'

    - role: geerlingguy.nginx
      become: true
      nginx_remove_default_vhost: true
      nginx_vhosts:
      - listen: "80 default_server"
        server_name: "example.com"
        root: "{{rails_app_root}}/{{rails_app_name}}/current/public"
        error_page: 500 502 503 504 /500.html
        extra_parameters: |
          location / {
             proxy_pass http://localhost:3000;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             proxy_set_header Host $http_host;
             proxy_redirect off;
          }
