---
  - name: install dependencies
    apt: name={{item}}
    become: true
    with_items:
      - git-all
      - libpq-dev

  - set_fact: app_name="{{rails_app_name}}-{{rails_env}}"
  - name: create necessary directories
    file:
      path="{{item}}"
      state=directory
      owner={{ansible_user_id}}
      group={{ansible_user_id}}
      recurse=yes
    become: true
    with_items:
      - "{{rails_app_root}}"

  - include: deploy.yml
    when: env != 'development'

  - include: development.yml
    when: env == 'development'
